import {
  BiBookHeart,
  BiCreditCard,
  BiEdit,
  BiFile,
  BiGift,
  BiImage,
  BiLogoProductHunt,
  BiSolidDashboard,
  BiSolidUserAccount,
  BiSolidLeftArrowSquare,
  BiSync,
  BiX,
  BiCategory,
  BiData,
  BiSolidRightArrowSquare,
  BiTrash,
  BiDollar,
  BiCoinStack,
  BiCoin,
  BiMoneyWithdraw,
  BiCamera,
  BiLoader,
  BiLockOpenAlt,
} from "react-icons/bi";

import { FaCartShopping, FaRegCircleUser } from "react-icons/fa6";
import { GoHomeFill, GoSearch } from "react-icons/go";
import { IoNotificationsOutline } from "react-icons/io5";
import { RiLogoutBoxLine } from "react-icons/ri";
import { AiFillCloseSquare } from "react-icons/ai";
const icons = {
  BiX,
  BiDollar,
  BiData,
  GoHomeFill,
  FaRegCircleUser,
  FaCartShopping,
  GoSearch,
  RiLogoutBoxLine,
  IoNotificationsOutline,
  BiSolidDashboard,
  BiSolidUserAccount,
  BiLogoProductHunt,
  BiGift,
  BiFile,
  BiCreditCard,
  BiSync,
  BiEdit,
  BiSolidLeftArrowSquare,
  BiSolidRightArrowSquare,
  BiBookHeart,
  BiImage,
  AiFillCloseSquare,
  BiTrash,
  BiCategory,
  BiCoinStack,
  BiCoin,
  BiMoneyWithdraw,
  BiCamera,
  BiLoader,
  BiLockOpenAlt,
};
export default icons;
