const actionTypes = {
  //Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",

  //User
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",
  GET_CART: "GET_CART",
  GET_CART_FAIL: "GET_CART_FAIL",
  CREATE_CHECKOUT: "CREATE_CHECKOUT",
  UPDATE_CHECKOUT: "UPDATE_CHECKOUT",

  //App
  GET_ROLES: "GET_ROLES",
  GET_PROVINCES: "GET_PROVINCES",
  GET_DISTRICTS: "GET_DISTRICTS",
  GET_WARDS: "GET_WARDS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_ADMIN_PRODUCTS: "GET_ADMIN_PRODUCTS",
};

export default actionTypes;
